-- For local development only

CREATE ROLE cr_labeling_admin WITH
ENCRYPTED PASSWORD 'Lugano2023'
LOGIN NOSUPERUSER CREATEDB NOCREATEROLE INHERIT NOREPLICATION
CONNECTION LIMIT -1;

CREATE DATABASE cr_labeling WITH
OWNER = cr_labeling_admin
ENCODING = 'UTF8'
CONNECTION LIMIT = -1;

CREATE EXTENSION tsm_system_rows;
